apiVersion: apps/v1
kind: Deployment
metadata:
  name: hachimitsu-random-bot
  labels:
    app: hachimitsu-random-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hachimitsu-random-bot
  template:
    metadata:
      labels:
        app: hachimitsu-random-bot
    spec:
      containers:
        - name: hachimitsu-random-bot
          image: ghcr.io/zel9278/hachimitsu-random-bot:main
          imagePullPolicy: IfNotPresent # because digest pinning
          envFrom:
            - secretRef:
                name: hrb-secrets
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE
      tolerations:
        - key: "low-spec"
          operator: "Equal"
          value: "E2.1.Micro"
          effect: "NoExecute"
