apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordbot-pow
  labels:
    app: discordbot-pow
  annotations:
    link.argocd.argoproj.io/external-link: https://github.com/eoeo-org/pow/blob/main/README.md#bot-追加-url
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discordbot-pow
  template:
    metadata:
      labels:
        app: discordbot-pow
    spec:
      containers:
        - name: discordbot-pow
          image: ghcr.io/eoeo-org/pow:3.14.26@sha256:e6ce614f8c4c03c13108f488751d11d20b0c705321c398e39d63ec315f8853ea
          envFrom:
            - secretRef:
                name: pow-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "130Mi"
              cpu: "15m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: mogyuchi.jp.node-restriction.kubernetes.io/network
                    operator: NotIn
                    values:
                      - detda
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
