apiVersion: batch/v1
kind: Job
metadata:
  generateName: migrate-deploy-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: migrate-deploy
          image: ghcr.io/eoeo-org/pow:3.14.14-migrate@sha256:7445d8d887d43b5486bc83322c884088e76b095be8f5e470bb709f1b42eae3d5
          envFrom:
            - secretRef:
                name: pow-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
  backoffLimit: 0
