apiVersion: batch/v1
kind: Job
metadata:
  generateName: migrate-deploy-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: migrate-deploy
          image: ghcr.io/eoeo-org/pow:3.14.44-migrate@sha256:d1463389c8db589721f72dde23967b23fab07c9ea86595ce040fb3cdde2e790e
          envFrom:
            - secretRef:
                name: pow-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: mogyuchi.jp.node-restriction.kubernetes.io/network
                    operator: NotIn
                    values:
                      - detda
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                      - oracle
  backoffLimit: 0
