apiVersion: batch/v1
kind: Job
metadata:
  generateName: migrate-deploy-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: migrate-deploy
          image: ghcr.io/eoeo-org/pow:3.14.27-migrate@sha256:7ab937f299f594995cd2e6d42a309a9ef62b3e2541fedd3fb7848872e1f04809
          envFrom:
            - secretRef:
                name: pow-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: mogyuchi.jp.node-restriction.kubernetes.io/network
                    operator: NotIn
                    values:
                      - detda
  backoffLimit: 0
