apiVersion: batch/v1
kind: Job
metadata:
  generateName: migrate-deploy-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: migrate-deploy
          image: ghcr.io/eoeo-org/pow:3.14.21-migrate@sha256:5374fdcd2fb34a02b795adb28443e9e0b9e7d60fde9fd8d8cc52a8391f5d6142
          envFrom:
            - secretRef:
                name: pow-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
  backoffLimit: 0
