apiVersion: batch/v1
kind: Job
metadata:
  generateName: migrate-deploy-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: migrate-deploy
          image: ghcr.io/eoeo-org/pow:3.12.0-migrate@sha256:ea29fe4e2749353ee139dcfe9ca669d3479a70b90672103a0a812590f47d05f2
          envFrom:
            - secretRef:
                name: pow-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
  backoffLimit: 0
