apiVersion: apps/v1
kind: Deployment
metadata:
  name: twibot-to-discord
  labels:
    app: twibot-to-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twibot-to-discord
  template:
    metadata:
      labels:
        app: twibot-to-discord
    spec:
      containers:
        - name: twibot-to-discord
          image: ghcr.io/zel9278/twibot-to-discord:main@sha256:c06bf4f27c09cacac59d258be486e38568368d4f3022cdea367158b7362869ab
          imagePullPolicy: IfNotPresent # because digest pinning
          env:
            - name: ADMIN
              value: "923158679006625802,615059426369339392"
          envFrom:
            - secretRef:
                name: ttd-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      tolerations:
        - key: "low-spec"
          operator: "Equal"
          value: "E2.1.Micro"
          effect: "NoExecute"
