apiVersion: apps/v1
kind: Deployment
metadata:
  name: twibot-to-discord
  labels:
    app: twibot-to-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twibot-to-discord
  template:
    metadata:
      labels:
        app: twibot-to-discord
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                      - oracle
      containers:
        - name: twibot-to-discord
          image: ghcr.io/eoeo-org/twibot-to-discord:main@sha256:a959832a7d1b09279924d5c9cbfb6f0b5b0f6df5521f3c2e4e50202ae3a6129b
          imagePullPolicy: IfNotPresent # because digest pinning
          env:
            - name: ADMIN
              value: "923158679006625802,325222935612620800,615059426369339392"
          envFrom:
            - secretRef:
                name: ttd-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            # runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      tolerations:
        - key: "low-spec"
          operator: "Equal"
          value: "E2.1.Micro"
          effect: "NoExecute"
        - effect: NoExecute
          key: agent
          operator: Exists
